spring:
    application:
        name: "configserver"
    profiles:
      #active: native
      active: git
    cloud:
        config:
            server:
              #native:
                #search-locations: "classpath:/config"
                #search-locations: "file:////Users//abhiramkancharla//Documents//config"
              git:
                uri: "https://github.com/abhi-05-sudo/config.git"
                default-label: main
                timeout: 5
                clone-on-start: true
                force-pull: true

        rabbitmq:
          host: "localhost"
          port: 5672
          username: "guest"
          password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
   readinessstate:
     enabled: true
   livenessstate:
     enabled: true
  endpoint:
   health:
     probes:
       enabled: true


encrypt:
    key: "12qw34as56zx"

server:
    port: 8071